# This is a config for E2B sandbox template.
# You can use template ID (qgy3x37zrp0rrcyficlh) or template name (vibe-nextjs-create) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-create") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-create") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-create')

team_id = "555ca36c-fcf6-4229-b0ec-cfe9591a3b80"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-create"
template_id = "qgy3x37zrp0rrcyficlh"
